### ISSUE TITLE
singular M^T M in G_step

### ISSUE THREAD

**Issue by mjvakili** [mjvakili/psfbasis#1]
line 109 of lsq.py:

M^T M is not invertible.

**Comment by mjvakili** [comment]
I'm going to switch to gradient descent for updating G.

**Comment by davidwhogg** [comment]
I don't see how that is possible.  Can you make the SVD of M^t M and see what the singular values are?

**Comment by mjvakili** [comment]
![eigen_values](https://cloud.githubusercontent.com/assets/2245056/7035309/2ab16eb0-dd55-11e4-82fc-f21c186bac64.png)

**Comment by mjvakili** [comment]
same plot with logarithmic x-axis only:

![eigen_values](https://cloud.githubusercontent.com/assets/2245056/7035404/2010fe16-dd56-11e4-9289-ee923240f3da.png)

**Comment by davidwhogg** [comment]
A tiny regularization would fix this. Try that too.

**Comment by mjvakili** [comment]
Yes, it works.
Ross pointed out that we can accelerate it significantly by bfgs optimizer since we can compute the gradient of the likelihood w.r.t G and give it to the optimizer.
